"""Correct questions mistakes

Revision ID: 781f8f7f5f67
Revises: 0b357b347b61
Create Date: 2025-01-25 21:32:41.709042

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "781f8f7f5f67"
down_revision: Union[str, None] = "0b357b347b61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("test_questions", "points", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("test_questions", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test_questions", sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column("test_questions", "points", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
